### ISSUE TITLE
給我熊熊的新聞

### ISSUE THREAD

**Issue by f30634f30634** [f30634f30634/test1104#3]
![image](https://user-images.githubusercontent.com/73588900/98108803-8a2dee80-1ed7-11eb-9530-0b8539f73ca0.png)

G奶女神熊熊(卓毓彤)挺過之前一連串負面風波後，似乎成長不少，就連身心靈也日漸茁壯，她昨(2)天在IG限時動態中透露自己拒絕一個想跟她拍照的人，「我今天成功拒絕了要來合照的人。如果你有看到還是跟你說聲抱歉。」她也表示自己常常為了討好別人就委屈自己，事後又超級後悔，「保護自己身心靈，學會說不」。

熊熊在限時動態中提到，曾經有朋友跟她說「私人時間你不想拍照就不要勉強自己。」當時聽到對方會直接拒絕合照時，她真的覺得這個舉動很勇敢，「因為我之前都覺得對身為公眾人物的我們來說，好像拒絕合照或是簽名是一種不對的行為。」

她表示對於一般人而言，拒絕別人似乎不是很困難，但熊熊心裡始終有一道跨不過去的障礙，「我總會因為怕被討厭、怕被不喜歡、怕被誤會很跩等等的各種原因，所以討好別人，總是委屈忍耐做很多自己並不想做的事情。」

比方說，當天狀態不好但還是接受合照了，或是明明酒量不好卻還是喝醉了，熊熊坦言事後都會超後悔，「覺得當時不應該逼迫自己、違背自己的內心，現在想想覺得好傻。」她也領悟到如果有人因此生氣，那也不是真心喜歡自己，「學會拒絕，學會說不，保護自己的身心靈。」

![image](https://user-images.githubusercontent.com/73588900/98108818-9154fc80-1ed7-11eb-9a4e-8feb714493e6.png)

**Comment by s9970233** [comment]
G奶女神熊熊(卓毓彤)挺過之前一連串負面風波後，似乎成長不少，就連身心靈也日漸茁壯，她昨(2)天在IG限時動態中透露自己拒絕一個想跟她拍照的人，「我今天成功拒絕了要來合照的人。如果你有看到還是跟你說聲抱歉。」她也表示自己常常為了討好別人就委屈自己，事後又超級後悔，「保護自己身心靈，學會說不」。


熊熊在限時動態中提到，曾經有朋友跟她說「私人時間你不想拍照就不要勉強自己。」當時聽到對方會直接拒絕合照時，她真的覺得這個舉動很勇敢，「因為我之前都覺得對身為公眾人物的我們來說，好像拒絕合照或是簽名是一種不對的行為。」

她表示對於一般人而言，拒絕別人似乎不是很困難，但熊熊心裡始終有一道跨不過去的障礙，「我總會因為怕被討厭、怕被不喜歡、怕被誤會很跩等等的各種原因，所以討好別人，總是委屈忍耐做很多自己並不想做的事情。」

比方說，當天狀態不好但還是接受合照了，或是明明酒量不好卻還是喝醉了，熊熊坦言事後都會超後悔，「覺得當時不應該逼迫自己、違背自己的內心，現在想想覺得好傻。」她也領悟到如果有人因此生氣，那也不是真心喜歡自己，「學會拒絕，學會說不，保護自己的身心靈。」

**Comment by f30634f30634** [comment]
![Uploading image.png…]()
