### ISSUE TITLE
我要一個G罩杯女星的新聞

### ISSUE THREAD

**Issue by f30634f30634** [f30634f30634/test1104#4]

**Comment by sandychao0** [comment]
![image](https://user-images.githubusercontent.com/73592584/98109052-e85ad180-1ed7-11eb-913e-0e797fb8738c.png)

台海關係緊張，共機近來頻繁侵擾台灣，根據國防部最新的公布資料顯示，自10月初以來共軍已經多達11次擾台的紀錄。被鄉民戲稱「舔共女王」的台灣藝人劉樂妍今卻在微博諷刺的說「我喜歡『武統』」，讓不少網友火大回嗆。


劉樂妍今在微博發文說，「我剛才在網上搜尋好吃的，突然發現北京有一家餐廳叫做梧桐，我不小心笑得嘴巴都咧到耳朵了，這個名字好，剛好我喜歡『武統』」，但劉樂妍今年初生病時，卻返台享用健保福利就醫開刀，被批評是吃裡扒外，讓不少網友相當生氣留言「佩服你的想像力」、「你敢上前線當女護士嗎？」

事實上，今年三月劉樂妍就在微博上公開表示「我就是極統派，而且我根本不想說任何廢話，就是支持武力統一」，今再度重申喜歡「武統」，網友紛紛氣喊「你可以不必回台灣了」、「什麼時候把她國籍註銷」、「這種人還敢回台灣看病」、「別再用台灣健保」、「不治治這小丑，她以為她隨便講都沒事」。
