### ISSUE TITLE
中華共和國 總統大選票數 再給一張小熊維尼的圖案

### ISSUE THREAD

**Issue by f30634f30634** [f30634f30634/test1104#5]

**Comment by sandychao0** [comment]
大陸全國人大會議今天上午選出了新一屆國家主席和中央軍事委員會主席，一如外界預期由唯一候選人習近平當選連任。而習近平的反貪大將王岐山則當選了國家副主席。兩人當選也宣告習王時代來臨。


中國大陸全大人民會議選出了新一屆國家領導人，毫無意外的唯一候選人習近平獲得2970名代表，全體贊成，連任國家主席和中央軍委主席，當選之後習近平還首次進行憲法宣誓，至於前中共中央政治局常委王岐山則以2969票贊成、1票反對，當選了中國大陸國家副主席，按照中共中央政治局，「七上八下」的慣例，常委滿68足歲就必須下台，去年19大後，王岐山就退出領導層，沒想到69歲的他閃電復出，還破格以普通黨員的身份當選國家副主席，外界認為應該和他協助習近平打貪有功有關，習近平和王岐山當選，宣告習王時代來臨，而先前人大還修憲取消了國家正副主席，任期限制讓習近平得以終身掌權引發強人獨裁的疑慮，其實不止中國大陸即將舉行總統大選的俄羅斯總統普丁修憲延長任期，還不斷回鍋執政，土耳其總統艾爾段也修憲擴權延長任期，北韓的金氏王朝至今地位依然穩固，令不少政治專家憂心，民主體制正受到前所未有的嚴峻挑戰。

![image](https://user-images.githubusercontent.com/73592584/98108733-708ca700-1ed7-11eb-891c-7dd32c38ea8b.png)

**Comment by f30634f30634** [comment]
![Uploading image.png…]()
